---
- name: apt update index
  become: yes
  apt: 
    update_cache: yes
  
- name: apt upgrade packages
  apt:
    name: "*"
    state: latest

- name: install apache2 
  apt:
    name: ['apache2', 'libapache2-mod-php']
    state: present
  notify:
    - restart apache

- name: start apache2 service
  systemd:
    name: apache2
    state: started


